### ISSUE TITLE
ffbinaries haven't been updated since ffmpeg-4.2.1

### ISSUE THREAD

**Issue by varenc** [vot/ffbinaries-prebuilt#14]
ffmpeg is now on version 4.4. Looks like the binaries haven't been updated for a year.

**Comment by cyberlimbo** [comment]
yeah.
i just created a thread about the same issue.

**Comment by vot** [comment]
Hi @varenc and @cyberlimbo,

Version 4.4.1 has now been added here - apologies for the delay!
