### ISSUE TITLE
linux cuda support

### ISSUE THREAD

**Issue by asasas234** [vot/ffbinaries-prebuilt#18]
hi, Hi, I hope to be able to support a Linux version of FFmpeg that supports CUDA.

**Comment by vot** [comment]
Hi @asasas234,

Apologies for the delay. Unfortunately after looking into this I have to let you know that this would not be possible / practical. 

ffmpeg compiled with CUDA support depends on the driver installed on the OS, meaning the version of the driver in the OS would need to be the exact same version as the one used during ffmpeg build. It wouldn't be practical as this would mean an almost infinite number of builds.
TBH I really wanted to support this scenario as well so I understand this will be rather disappointing.

What I can recommend as an alternative is utilising Docker for such workloads as this will ensure the driver version consistent between the OS and ffmpeg. There are a few of such images around, in my past experiments I had success with Julien Rottenberg's builds (https://github.com/jrottenberg/ffmpeg).
