### ISSUE TITLE
 FriBiDi upgrade

### ISSUE THREAD

**Issue by cDQK** [vot/ffbinaries-prebuilt#8]
can you upgrade the FriBiDi version?
I currently using ffmpeg version 3.3, It behaves badly
![Screenshot_2020-04-24-14-33-10](https://user-images.githubusercontent.com/55192366/80186685-fb473c00-8640-11ea-9595-f95866dae541.jpg)
the fonts.conf file
![Screenshot_2020-04-24-14-33-11](https://user-images.githubusercontent.com/55192366/80186742-15811a00-8641-11ea-9336-025146bdb545.jpg)

**Comment by vot** [comment]
Hi @cDQK, unfortunately I don't compile the binaries myself and simply repackage them for convenience.

Have you checked if newer versions of ffmpeg have the same issue?

**Comment by cDQK** [comment]
ok, later I comment paragraph of the "its" and "description"  this problem solved!
